### ISSUE TITLE
Bookmark description from selection

### ISSUE THREAD

**Issue by danesparza** [samclark/pinboard#4]
When you add a new bookmark, I'd like to see the bookmark description get set from whatever was selected in the page.

**Comment by lzrbm** [comment]
Hi,

Has this feature broke again or is it no longer a part of this extension? I just downloaded from Chrome Web Store and everything is working fine except for the selection-to-description piece.

**Comment by samclark** [comment]
I don't work on this project much these days (as you can probably tell from the commit history) but I just did a fresh install of the extension and it seemed to work. 

If it's still not working please let me know the following:

- Which operating system you are using
- The version of Google Chrome
- URL of the website that doesn't work

Thanks

**Comment by lzrbm** [comment]
Hey. Thanks for the response.

I'm using Windows 10 and Chrome is up to date (Version 48.0.2564.103 m).
It did start to work after I opened a new Chrome window.  Later though it didn't again but i'm not sure what caused the change. 

I just re-installed and opened a new window. Worked the [first time](http://www.themarysue.com/). Followed a link to [this page](http://www.themarysue.com/x-files-newbie-recap-leonard-betts/) but didn't work. Returned to that first main page and it did work. Back to linked page, did not work. Not really sure. I tried six articles from this site - five didn't work, [one did](http://www.themarysue.com/netflix-and-no-chill-on-relationships/).

Different site - Guardian. Had trouble with [this page](http://www.theguardian.com/us-news/live/2016/feb/08/donald-trump-bernie-sanders-new-hampshire-primary-live) but [this one](http://www.theguardian.com/us-news/2016/feb/08/beyonce-dancers-black-lives-matter-super-bowl-half-time-show-mario-woods-fatal-shooting) worked. 

I opened Livejournal links and quite a few worked until one didn't. So I guess it seems inconsistent  but I can't tell why. Thanks for checking it out. :)

**Comment by samclark** [comment]
It seems like a lot of other extensions are also having trouble getting the selected text. Google Chrome doesn't have an API to get the selected text so we are left to try and get it ourselves using content scripts. These scripts seems to have problems with webpages that use iframes (and probably other things too).

I've pushed an update to the extension (2.2.4) that uses a different approach to get the selected text but I don't have a lot of faith that it will work for every scenario. Hopefully it's better though.

Try out the new version and let me know the details of any cases where it still doesn't work.

Thanks

**Comment by lzrbm** [comment]
Thanks for checking it out. I stress tested the new one a bit and it picked up the text on the 15 or so I attempted. :)  Very pleased. I can keep you posted. Thanks for doing that - much appreciated.

**Comment by samclark** [comment]
Cool thanks.
